version: '3'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "9060:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: nihad
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: nihad
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - custom_network

volumes:
  wordpress_data:
  db_data:

networks:
  custom_network:
    driver: bridge
